/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.37
 * Generated at: 2017-03-12 21:37:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import br.com.MyHouseTech.model.Usuario;

public final class cadastro_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("br.com.MyHouseTech.model.Usuario");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\t\t<title>Cadastro - My House Tech</title>\n");
      out.write("\t\t<meta charset=\"ISO-8859-1\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\t\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<script src=\"javascript/jquery.mask.min.js\"></script>\n");
      out.write("\t\t<script src=\"javascript/cadastro.js\"></script>\n");
      out.write("\t</head>\n");
      out.write("\t<body>\n");
      out.write("\t\t<!-- Inicio Header -->\n");
      out.write("\t\t<header id=\"header\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-xs-12\">\n");
      out.write("\t\t\t\t\t  <a class=\"logoSite\" title=\"My house tech\" href=\"areaRestrita.jsp\"></a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 hidden-xs userInfo\">\n");
      out.write("\t\t\t\t\t\t<form name=\"form\"\tmethod=\"Post\"\taction=\"Logout\">\n");
      out.write("\t\t\t\t\t\t\tBem vindo(a) \n");
      out.write("\t\t\t\t\t\t\t");
 Usuario objUsuario = (Usuario) session.getAttribute("objUser"); 
								out.print(objUsuario.getNome()); 
							
      out.write("\n");
      out.write("\t\t\t\t\t\t\t- <input type=\"submit\" name=\"Submit\" class=\"btnLogout\" value=\"Sair\"/>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- Fim Header -->\n");
      out.write("\t\t<!-- Inicio Menu -->\n");
      out.write("\t\t<div class=\"mainMenu\">\n");
      out.write("\t\t\t<nav class=\"container\">\n");
      out.write("\t\t\t\t<ul class=\"first fLeft\">\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"Minhas informações/\" title=\"Minhas informações\">Minhas informações</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t\t<li>\n");
      out.write("\t\t\t\t\t\t<a href=\"Controle de consumo/\" title=\"Controle de consumo\">Controle de consumo</a>\n");
      out.write("\t\t\t\t\t</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Fim Menu -->\n");
      out.write("\t\t<!-- Inicio conteudo -->\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\">\n");
      out.write("\t\t\t\t\t<h2>Formulário de cadastro</h2>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"row dispList\">\n");
      out.write("\t\t\t\t<div  class=\"col-md-3 hidden-xs\"></div>\n");
      out.write("\t\t\t\t<div  class=\"col-xs-12 col-md-12\">\n");
      out.write("\t\t\t\t\t<div role=\"containerCadastro\">\n");
      out.write("\t\t\t\t\t<form name=\"form\"\tmethod=\"Post\"\taction=\"Cadastro\" onsubmit=\"validaCampos(this); return false;\">\n");
      out.write("\t\t\t\t\t\t<input id=\"nome\"\t\t\ttype=\"text\" \t\tname=\"nome\" \t\t\tvalue=\"Nome\" \t\t\tmaxlength=\"50\"\t\tonfocus=\"if (this.value == 'Nome')\t\t\t{this.value = '';}\" \t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Nome';}\"\t\t\t\t\t\t\tclass=\"margin30Bottom\">\n");
      out.write("\t\t\t\t\t\t<input id=\"sobrenome\"\ttype=\"text\" \t\tname=\"sobrenome\" \t\tvalue=\"Sobrenome\" \tmaxlength=\"150\"\tonfocus=\"if (this.value == 'Sobrenome')\t{this.value = '';}\" \t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Sobrenome';}\"\t\t\t\t\tclass=\"margin30Bottom\">\n");
      out.write("\t\t\t\t\t\t<input id=\"email\"\t\t\ttype=\"text\" \t\tname=\"email\" \t\t\tvalue=\"E-mail\" \t\tmaxlength=\"150\"\tonfocus=\"if (this.value == 'E-mail')\t\t{this.value = '';}\" \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"margin30Bottom email\">\n");
      out.write("\t\t\t\t\t\t<input id=\"cpf\"\t\t\ttype=\"text\" \t\tname=\"cpf\" \t\t\t\tvalue=\"CPF\" \t\t\tmaxlength=\"14\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'CPF';}\"\t\t\t\t\t\t\tclass=\"margin30Bottom cpf\">\n");
      out.write("\t\t\t\t\t\t<input id=\"endereco\"\t\ttype=\"text\" \t\tname=\"endereco\"\t\tvalue=\"Endereço\"\t\tmaxlength=\"200\"\tonfocus=\"if (this.value == 'Endereço')\t\t{this.value = '';}\"\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Endereço';}\"\t\t\t\t\tclass=\"margin30Bottom\">\n");
      out.write("\t\t\t\t\t\t<input id=\"telefone\"\t\ttype=\"text\" \t\tname=\"telefone\"\t\tvalue=\"Telefone\"\t\tmaxlength=\"14\"\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Telefone';}\"\t\t\t\t\tclass=\"margin30Bottom telefone\">\n");
      out.write("\t\t\t\t\t\t<input id=\"login\"\t\t\ttype=\"text\" \t\tname=\"login\" \t\t\tvalue=\"Login\" \t\t\tmaxlength=\"100\"\tonfocus=\"if (this.value == 'Login')\t\t\t{this.value = '';}\" \t\t\t\t\t\t\t\tonblur=\"if (this.value == '') {this.value = 'Login';}\"\t\t\t\t\t\tclass=\"margin30Bottom\">\n");
      out.write("\t\t\t\t\t\t<input id=\"senha\"\t\t\ttype=\"text\"\t\t\tname=\"senha\" \t\t\tvalue=\"Senha\" \t\t\tmaxlength=\"200\"\tonfocus=\"if (this.value == 'Senha')\t\t\t{this.value = '';this.type='password';}\"\tonblur=\"if (this.value == '') {this.value = 'Senha';this.type='text'}\"\tclass=\"margin30Bottom\">\n");
      out.write("\t\t\t\t\t\t<div   id=\"tipoPlano\">Tipo de plano</div>\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" name=\"optradio\" value=\"0\">Plano Basic</label>\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" name=\"optradio\" value=\"1\">Plano Premium</label>\n");
      out.write("\t\t\t\t\t\t<label class=\"radio-inline\"><input type=\"radio\" name=\"optradio\" value=\"2\">Plano Pro</label>\n");
      out.write("\t\t\t\t\t\t<!--input id=\"password\" \ttype=\"text\"\t\t\tname=\"password\" \tvalue=\"Password\" \tonfocus=\"this.value = '';\"  onblur=\"if (this.value == '') {this.value = 'Password';}\"-->\n");
      out.write("\t\t\t\t\t\t<div class=\"button-row\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"submit\" name=\"Submit\" value=\"Cadastrar\"\tclass=\"btnCadastro\">\n");
      out.write("\t\t\t\t\t\t\t<!--input type=\"button\" class=\"reset\" \t\tvalue=\"Esqueci a senha\"-->\n");
      out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div  class=\"col-md-3 hidden-xs\"></div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- Fim conteudo -->\n");
      out.write("\t\t<!-- Inicio footer -->\n");
      out.write("\t\t<footer id=\"footer\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<p>&copy 2016 Login Form. All Rights Reserved | Design by Gabriel Andrade</p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- Fim footer -->\n");
      out.write("\t</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
